//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeloitteNF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasFiscais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotasFiscais()
        {
            this.ItensNotasFiscais = new HashSet<ItensNotasFiscais>();
        }
    
        public int NotaFiscal_id { get; set; }
        public int Cliente_id { get; set; }
        public System.DateTime Data { get; set; }
        public Nullable<bool> Emitida { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItensNotasFiscais> ItensNotasFiscais { get; set; }
    }
}
