//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeloitteNF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produtos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produtos()
        {
            this.ItensNotasFiscais = new HashSet<ItensNotasFiscais>();
        }
    
        public int Produto_id { get; set; }
        public string Nome { get; set; }
        public string Unidade { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public Nullable<int> Fornecedor_id { get; set; }
    
        public virtual Fornecedores Fornecedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItensNotasFiscais> ItensNotasFiscais { get; set; }
    }
}
